name: Portage CD
description: Code Scan + Image Build + Image Scan + Image Publish + Validation
inputs:
  build_args:
    description: Comma seperated list of build time variables
  build_dir:
    description: The build directory to using during an image build
    default: .
  bundle_publish_enabled:
    description: Enable/Disable gatecheck artifact bundle publish task
    default: "1"
  bundle_publish_tag:
    description: The full image tag for the target gatecheck bundle image blob
    default: my-app/artifact-bundle:latest
  code_scan_enabled:
    description: Enable/Disable the code scan pipeline
    default: "1"
  config_file:
    description: The path to a config file to use when executing portage
  container_registry:
    description: The container registry to login to (used if no DOCKER_AUTH_JSON is provided)
  deploy_enabled:
    description: Enable/Disable the deploy pipeline
    default: "1"
  docker_auth_json:
    description: The Docker config with credentials that will be used for ~/.docker/config.json (takes precedence over explicit registry credentials)
  dockerfile:
    description: The Dockerfile/Containerfile to use during an image build
    default: Dockerfile
  image_build_enabled:
    description: Enable/Disable the image build pipeline
    default: "1"
  image_publish_enabled:
    description: Enable/Disable the image publish pipeline
    default: "1"
  image_scan_enabled:
    description: Enable/Disable the image scan pipeline
    default: "1"
  platform:
    description: The target platform for build
  registry_token:
    description: The token or password for the container registry (used if no DOCKER_AUTH_JSON is provided)
  registry_user:
    description: The username for the container registry (used if no DOCKER_AUTH_JSON is provided)
  semgrep_rules:
    description: Semgrep ruleset manual override
    default: p/default
  tag:
    description: The full image tag for the target container image
    default: my-app:latest
  target:
    description: The target build stage to build (e.g., [linux/amd64])
runs:
  using: docker
  image: docker://ghcr.io/easy-up/portage-action:podman-v0.0.1-rc.8
  args: []
  env:
    CONTAINER_REGISTRY: ${{ inputs.container_registry }}
    DOCKER_AUTH_JSON: ${{ inputs.docker_auth_json }}
    PORTAGE_CODE_SCAN_ENABLED: ${{ inputs.code_scan_enabled }}
    PORTAGE_CODE_SCAN_SEMGREP_RULES: ${{ inputs.semgrep_rules }}
    PORTAGE_CONFIG: ${{ inputs.config_file }}
    PORTAGE_DEPLOY_ENABLED: ${{ inputs.deploy_enabled }}
    PORTAGE_IMAGE_BUILD_ARGS: ${{ inputs.build_args }}
    PORTAGE_IMAGE_BUILD_DIR: ${{ inputs.build_dir }}
    PORTAGE_IMAGE_BUILD_DOCKERFILE: ${{ inputs.dockerfile }}
    PORTAGE_IMAGE_BUILD_ENABLED: ${{ inputs.image_build_enabled }}
    PORTAGE_IMAGE_BUILD_PLATFORM: ${{ inputs.platform }}
    PORTAGE_IMAGE_BUILD_TARGET: ${{ inputs.target }}
    PORTAGE_IMAGE_BUNDLE_PUBLISH_ENABLED: ${{ inputs.bundle_publish_enabled }}
    PORTAGE_IMAGE_PUBLISH_BUNDLE_TAG: ${{ inputs.bundle_publish_tag }}
    PORTAGE_IMAGE_PUBLISH_ENABLED: ${{ inputs.image_publish_enabled }}
    PORTAGE_IMAGE_SCAN_ENABLED: ${{ inputs.image_scan_enabled }}
    PORTAGE_IMAGE_TAG: ${{ inputs.tag }}
    REGISTRY_TOKEN: ${{ inputs.registry_token }}
    REGISTRY_USER: ${{ inputs.registry_user }}
