name: Build portage images for use in GitHub actions.
run-name: "Build Portage CD Action Images"
permissions:
  contents: read
  packages: write
  checks: write
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
jobs:
  image_delivery:
    runs-on: ubuntu-latest
    name: Build Image with Docker Action
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6

      - name: Set outputs
        id: vars
        run: |
          image_repo=ghcr.io/easy-up/portage-action
          image_tag=${GITHUB_SHA::8}
          # If on a git tag like vx.x.x, change the image tag to reflect
          echo "GITHUB_REF: $GITHUB_REF"
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            image_tag=${GITHUB_REF/refs\/tags\//}
          elif [[ $GITHUB_REF == refs/heads/debug* ]]; then
            image_tag=${GITHUB_REF/refs\/heads\//}
          fi
          # Image Names
          echo "image_name=$image_repo:$image_tag" >> $GITHUB_OUTPUT 
          echo "podman_image_name=$image_repo:podman-$image_tag" >> $GITHUB_OUTPUT 
          # Build Variables
          echo "version=$(cat PORTAGE_VERSION)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: ./image-build-scan-publish/docker/
          push: true
          tags: ${{ steps.vars.outputs.image_name }}
          build-args: "VERSION=${{ steps.vars.outputs.version }}"

      - name: Build and push podman target
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: ./image-build-scan-publish/podman/
          push: true
          tags: ${{ steps.vars.outputs.podman_image_name }}
          build-args: "VERSION=${{ steps.vars.outputs.version }}"

      - name: job summary
        shell: bash
        run: |
          echo "## Docker Action Image Build and Push Summary" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Image (Docker CLI): ${{ steps.vars.outputs.image_name }}" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Image (Podman CLI): ${{ steps.vars.outputs.podman_image_name }}" >> $GITHUB_STEP_SUMMARY
